"""ComfyUI YuE2 staged generation nodes."""

from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .artifact_nodes import NODE_CLASS_MAPPINGS as ARTIFACT_NODES, NODE_DISPLAY_NAME_MAPPINGS as ARTIFACT_NAMES
from .score_nodes import NODE_CLASS_MAPPINGS as SCORE_NODES, NODE_DISPLAY_NAME_MAPPINGS as SCORE_NAMES

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **ARTIFACT_NODES, **SCORE_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **ARTIFACT_NAMES, **SCORE_NAMES}

WEB_DIRECTORY = "./web/dist"
